# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LiveChatSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'CometChatPro', '~> 1.8.7'
  	pod 'SDWebImage', '~> 4.0'

  # Pods for LiveChatSwift

  target 'LiveChatSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveChatSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
